### ISSUE TITLE
Seeking knowledge

### ISSUE THREAD

**Issue by melsonmascarenhas** [ZerBea/hcxbtdumptool#3]
What areas in the C programming language do I need to learn in order to create tools like this?

**Comment by ZerBea** [comment]
Beside C coding skills it is mandatory to be familiar e.g. with
Linux kernel documentation:
https://www.kernel.org/doc/html/latest/
bluetooth protocol:
https://www.bluetooth.com/learn-about-bluetooth/tech-overview/
802.11 protocol:
https://community.fs.com/blog/802-11-standards-explained.html
and of course, C:
https://www.codecademy.com/learn/learn-c

Please open a discussion, because it is not a bug and this is a bug tracker.
https://github.com/ZerBea/hcxdumptool/discussions

**Comment by melsonmascarenhas** [comment]
Sure, and Thank you for the details.
